### ISSUE TITLE
objects and th: not recognized 

### ISSUE THREAD

**Issue by chainc00de** [Urodacus/tasksManager#9]
already have  thymeleaf dependency in the pom.xml 

```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>
```

and in the template  `<html lang="en" xmlns:th="https://www.thymeleaf.org">`

but it gave me the samme error

**Comment by Urodacus** [comment]
I think you are using intellij 
there is a simple  walkaround you can do and this is just by editing the thymeleaf url  like that 

`<html lang="en" xmlns:th="https://thymeleaf.org">`

**Comment by chainc00de** [comment]
thanks this solved the issue
